- id: doi:10.1371/journal.pcbi.1007128
  type: paper
  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2020-12-4
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review

- id: doi:10.1002/ijc.30887
  image: https://onlinelibrary.wiley.com/cms/asset/c11c6ced-4c25-4d4a-8800-39714e45894a/ijc30887-fig-0001-m.jpg

- id: doi:10.4137/CIN.S14027
  image: https://journals.sagepub.com/cms/10.4137/CIN.S14027/asset/images/large/10.4137_cin.s14027-fig2.jpeg

- id: doi:10.1371/journal.pone.0094045

- id: doi:10.1371/journal.pone.0062982

- id: doi:10.1371/journal.pone.0047839

- id: doi:10.1371/journal.pone.0051407
  image: https://ndownloader.figstatic.com/files/285927/preview/285927/preview.jpg

- id: doi:10.21541/apjes.403727